version: "3.8"

services:

  app:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "5005:5005"
    environment:
      - SQLALCHEMY_DATABASE_URI=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}

  postgres:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}



