"""Users upgrade

Revision ID: 55dd7ec5f1f8
Revises: 5aed9c8ce322
Create Date: 2022-11-04 21:56:31.188757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55dd7ec5f1f8'
down_revision = '5aed9c8ce322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###
