"""UsersRegex class

Revision ID: d52a2e05e107
Revises: 64f9b753e8b6
Create Date: 2022-11-16 23:57:47.188295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52a2e05e107'
down_revision = '64f9b753e8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_regex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regex', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_regex_created'), 'users_regex', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_regex_created'), table_name='users_regex')
    op.drop_table('users_regex')
    # ### end Alembic commands ###
